seiza_name_dict = {
    'Andromeda': 'アンドロメダ座',
    'Antlia': 'ポンプ座',
    'Apus': 'ふうちょう座',
    'Aquila': 'わし座',
    'Aquarius': 'みずがめ座',
    'Ara': 'さいだん座',
    'Aries': 'おひつじ座',
    'Auriga': 'ぎょしゃ座',
    'Boötes': 'うしかい座',
    'Caelum': 'ちょうこくぐ座',
    'Camelopardalis': 'きりん座',
    'Capricornus': 'やぎ座',
    'Carina': 'りゅうこつ座',
    'Cassiopeia': 'カシオペヤ座',
    'Centaurus': 'ケンタウルス座',
    'Cepheus': 'ケフェウス座',
    'Cetus': 'くじら座',
    'Chamaleon': 'カメレオン座',
    'Circinus': 'コンパス座',
    'Canis Major': 'おおいぬ座',
    'Canis Minor': 'こいぬ座',
    'Cancer': 'かに座',
    'Columba': 'はと座',
    'Coma Berenices': 'かみのけ座',
    'Corona Australis': 'みなみのかんむり座',
    'Corona Borealis': 'かんむり座',
    'Crater': 'コップ座',
    'Crux ': 'みなみじゅうじ座',
    'Corvus': 'からす座',
    'Canes Venatici': 'りょうけん座',
    'Cygnus': 'はくちょう座',
    'Delphinus': 'いるか座',
    'Dorado': 'かじき座',
    'Draco': 'りゅう座',
    'Equuleus': 'こうま座',
    'Eridanus': 'エリダヌス座',
    'Fornax': 'ろ座',
    'Gemini': 'ふたご座',
    'Grus': 'つる座',
    'Hercules': 'ヘルクレス座',
    'Horologium': 'とけい座',
    'Hydra': 'うみへび座',
    'Hydrus': 'みずへび座',
    'Indus': 'インディアン座',
    'Lacerta': 'とかげ座',
    'Leo': 'しし座',
    'Lepus': 'うさぎ座',
    'Libra': 'てんびん座',
    'Leo Minor': 'こじし座',
    'Lupus': 'おおかみ座',
    'Lynx': 'やまねこ座',
    'Lyra': 'こと座',
    'Mensa': 'テーブル山座',
    'Microscopium': 'けんびきょう座',
    'Monoceros': 'いっかくじゅう座',
    'Musca': 'はえ座',
    'Norma': 'じょうぎ座',
    'Octans': 'はちぶんぎ座',
    'Ophiucus': 'へびつかい座', 
    'Orion': 'オリオン座',
    'Pavo': 'くじゃく座',
    'Pegasus': 'ペガスス座',
    'Perseus': 'ペルセウス座',
    'Phoenix': 'ほうおう座',
    'Pictor': 'がか座',
    'Pisces Austrinus': 'みなみのうお座',
    'Pisces': 'うお座',
    'Puppis': 'とも座',
    'Pyxis': 'らしんばん座',
    'Reticulum': 'レチクル座',
    'Sculptor': 'ちょうこくしつ座',
    'Scorpius': 'さそり座',
    'Scutum': 'たて座',
    'Serpens': 'へび座',
    'Sextans': 'ろくぶんぎ座',
    'Sagitta': '矢座',
    'Sagittarius': 'いて座',
    'Taurus': 'おうし座',
    'Telescopium': 'ぼうえんきょう座',
    'Triangulum Australe': 'みなみのさんかく座',
    'Triangulum': 'さんかく座',
    'Tucana': 'きょしちょう座',
    'Ursa Major': 'おおぐま座',
    'Ursa Minor': 'こぐま座',
    'Vela': '帆座',
    'Virgo': 'おとめ座',
    'Volans': 'とびうお座',
    'Vulpecula': 'こぎつね座'
}
